# Generated by Django 5.0 on 2024-01-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PostModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "is_free",
                    models.BooleanField(default=False, verbose_name="is free?"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="posts/", verbose_name="image"
                    ),
                ),
                (
                    "publish_date",
                    models.DateField(auto_now_add=True, verbose_name="published date"),
                ),
                (
                    "views_count",
                    models.IntegerField(default=0, verbose_name="views count"),
                ),
            ],
            options={
                "verbose_name": "post",
                "verbose_name_plural": "posts",
            },
        ),
    ]
