# Generated by Django 5.0 on 2024-01-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmodel",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="views count"),
        ),
    ]
